/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheAltaiRouteImport } from './routes/the-altai'
import { Route as IndexRouteImport } from './routes/index'

const TheAltaiRoute = TheAltaiRouteImport.update({
  id: '/the-altai',
  path: '/the-altai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/the-altai': typeof TheAltaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/the-altai': typeof TheAltaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/the-altai': typeof TheAltaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/the-altai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/the-altai'
  id: '__root__' | '/' | '/the-altai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TheAltaiRoute: typeof TheAltaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-altai': {
      id: '/the-altai'
      path: '/the-altai'
      fullPath: '/the-altai'
      preLoaderRoute: typeof TheAltaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TheAltaiRoute: TheAltaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
